### ISSUE TITLE
Failing to deploy canisters

### ISSUE THREAD

**Issue by thomaskral** [buildwithjuno/emulator#1]
Hello, I am trying to setup the emulator and I am receiving this output with an error after running `./junolator deploy`:

```
Creating a wallet canister on the local network.
The wallet canister on the "local" network for user "default" is "rwlgt-iiaaa-aaaaa-aaaaa-cai"
Deploying: internet_identity
Creating canisters...
Creating canister internet_identity...
internet_identity canister created with canister id: rrkah-fqaaa-aaaaa-aaaaq-cai
Building canisters...
Installing canisters...
Creating UI canister on the local network.
The UI canister on the "local" network is "ryjl3-tyaaa-aaaaa-aaaba-cai"
Installing code for canister internet_identity, with canister ID rrkah-fqaaa-aaaaa-aaaaq-cai
Deployed canisters.
URLs:
  Backend canister via Candid interface:
    internet_identity: http://127.0.0.1:8000/?canisterId=ryjl3-tyaaa-aaaaa-aaaba-cai&id=rrkah-fqaaa-aaaaa-aaaaq-cai
Deploying: satellite
Creating canisters...
Creating canister satellite...
satellite canister created with canister id: r7inp-6aaaa-aaaaa-aaabq-cai
Building canisters...
Installing canisters...
Installing code for canister satellite, with canister ID r7inp-6aaaa-aaaaa-aaabq-cai
Error: Failed while trying to deploy canisters.
Caused by: Failed while trying to deploy canisters.
  Failed while trying to install all canisters.
    Failed to install wasm module to canister 'satellite'.
      Failed to install wasm in canister 'r7inp-6aaaa-aaaaa-aaabq-cai'.
        Failed to install wasm.
          The Replica returned an error: code 5, message: "Canister r7inp-6aaaa-aaaaa-aaabq-cai trapped explicitly: failed to decode call arguments: Custom(Cannot parse header 

Caused by:
    binary parser error: io error)"

**************************************************
* Satellite: r7inp-6aaaa-aaaaa-aaabq-cai         *
* Internet identity: rrkah-fqaaa-aaaaa-aaaaq-cai *
**************************************************

Your JS initialization code:

await initJuno({
  satelliteId: "r7inp-6aaaa-aaaaa-aaabq-cai",
  localIdentityCanisterId: "rrkah-fqaaa-aaaaa-aaaaq-cai",
});
```

Do you have an idea how to fix this?

Also it seems like there is a dependency missing in the `package.json`. When running `./junolator config` it complaints that `@dfinity/candid` can't be found.

And one needs to have `didc` installed, otherwise you will receive `./junolator: line 9: didc: command not found`

Node version: 18.15.0
DFX version: 0.13.1

**Comment by peterpeterparker** [comment]
> Also it seems like there is a dependency missing in the package.json. When running ./junolator config it complaints that @dfinity/candid can't be found.
> 
> And one needs to have didc installed, otherwise you will receive ./junolator: line 9: didc: command not found

Hi @thomaskral, well spotted, I think you found the two issues or two things that are missing in the script.

1. `didc` - the Candid CLI - is required to encode the principal when deploying the satellite (did not find any other solution so far, my questions on the forum are open). I'll add a note in the "Installation" chapter of the README.

It can be downloaded there -> https://github.com/dfinity/candid/releases

This will solve the error you faced `trapped explicitly: failed to decode call arguments`

2. `npm ci` is missing in the script, this will solve the `config` issue

**Comment by peterpeterparker** [comment]
Note: if you have a better idea and solution than using `didc` to encode the principal for the dfx deploy command, would love to hear it!

**Comment by thomaskral** [comment]
Hey @peterpeterparker, thanks for your quick response. It is working fine now.

My mistake was using a script I have found on dfinity forums to install the `didc`, which seems to install the wrong file or version.

When installing it manually from your provided link, it is working 👍🏻

**Comment by peterpeterparker** [comment]
Done. Thanks again 👍
